In [1]:
import pandas as pd

In [2]:
import numpy as np

In [27]:
sim10 = pd.read_csv("sim_sub10.csv")

In [4]:
sim10

,Unnamed: 0,tp,acc,Euclidean_dist,spec_dist,edit,netsmile
0,0,0.5,0.555556,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",3.009274,5.0,23.114263
1,1,0.6,0.600000,"(0, 0)\t1.7320508075688772\n (1, 1)\t1.4142...",1.607356,5.0,23.036300
2,2,0.7,0.636364,"(1, 1)\t1.0\n (1, 2)\tnan\n (2, 1)\tnan\n ...",1.514952,2.0,20.815851
3,3,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 4)\tnan\n ...",1.704043,7.0,20.847240
4,4,0.6,0.500000,"(0, 0)\t1.0\n (0, 2)\tnan\n (1, 1)\t1.0\n ...",0.968371,4.0,20.697713
5,5,0.7,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.704043,7.0,23.683258
6,6,0.6,0.545455,"(0, 0)\t2.0\n (0, 2)\t1.0\n (0, 4)\tnan\n ...",1.607356,7.0,23.036300
7,7,0.7,0.500000,"(0, 0)\t1.7320508075688772\n (0, 3)\tnan\n ...",1.704043,7.0,23.683258
8,8,0.6,0.600000,"(0, 0)\t1.7320508075688772\n (0, 3)\tnan\n ...",1.704043,7.0,20.847240
9,9,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.414214,5.0,22.226172
10,10,0.5,0.555556,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.414214,5.0,22.226172
11,11,0.6,1.000000,"(0, 0)\t1.4142135623730951\n (0, 2)\t1.0\n ...",4.419034,4.0,25.308363
12,12,0.6,0.666667,"(0, 0)\t1.7320508075688772\n (0, 2)\t1.0\n ...",3.325016,5.0,24.202346
13,13,0.5,0.416667,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.514952,6.0,20.815851
14,14,0.5,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.704043,7.0,20.847240
15,15,0.7,0.777778,"(0, 0)\t1.7320508075688772\n (0, 2)\t1.0\n ...",3.009274,4.0,22.524219
16,16,0.5,1.000000,"(0, 0)\t1.4142135623730951\n (0, 2)\t1.0\n ...",5.477226,5.0,25.000000
17,17,0.7,0.636364,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.607356,4.0,21.694556
18,18,0.5,0.714286,"(0, 0)\t1.4142135623730951\n (1, 1)\t1.4142...",3.325016,5.0,24.202346
19,19,0.5,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.704043,7.0,20.847240
20,20,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.514952,4.0,24.023737
21,21,0.7,0.875000,"(2, 2)\t1.0\n (2, 4)\t1.0\n (3, 3)\t1.4142...",2.281076,2.0,24.285558
22,22,0.7,0.875000,"(1, 1)\t1.4142135623730951\n (2, 2)\t1.4142...",2.140933,4.0,23.673874
23,23,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",1.514952,4.0,24.023737
24,24,0.6,0.750000,"(0, 0)\t1.4142135623730951\n (0, 4)\tnan\n ...",3.325016,5.0,24.202346
25,25,0.6,0.666667,"(0, 0)\t1.0\n (0, 2)\tnan\n (0, 3)\t1.0\n ...",3.009274,5.0,26.335117
26,26,0.7,0.500000,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",3.325016,5.0,23.868982
27,27,0.5,0.625000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.248495,6.0,25.085856
28,28,0.6,0.600000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",2.281076,4.0,24.285558
29,29,0.6,0.600000,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",3.009274,5.0,23.114263
30,30,0.6,0.857143,"(0, 0)\t1.0\n (0, 3)\t1.0\n (2, 2)\t1.0\n ...",3.325016,3.0,24.202346
31,31,0.5,0.714286,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",3.325016,7.0,24.202346
32,32,0.5,0.625000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.009274,7.0,26.335117
33,33,0.6,0.545455,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",1.704043,5.0,20.847240
34,34,0.7,0.500000,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",2.281076,4.0,23.059793
35,35,0.6,0.545455,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.748064,7.0,20.206879
36,36,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",1.607356,5.0,23.036300
37,37,0.7,0.875000,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",3.325016,3.0,24.202346
38,38,0.7,0.636364,"(0, 0)\t1.4142135623730951\n (0, 2)\t1.0\n ...",1.607356,4.0,25.923601
39,39,0.7,0.700000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.704043,5.0,20.847240
40,40,0.8,0.571429,"(0, 0)\t1.7320508075688772\n (0, 1)\t1.0\n ...",3.009274,7.0,26.240807
41,41,0.7,0.583333,"(0, 0)\t1.0\n (0, 3)\tnan\n (0, 4)\tnan\n ...",1.704043,5.0,20.847240
42,42,0.6,0.545455,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",1.607356,5.0,23.036300
43,43,0.7,0.538462,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.607356,7.0,22.949618
44,44,0.6,0.666667,"(0, 0)\t1.4142135623730951\n (0, 4)\tnan\n ...",1.607356,5.0,23.036300
45,45,0.5,0.625000,"(0, 0)\t1.4142135623730951\n (1, 1)\t1.4142...",2.140933,4.0,23.673874
46,46,0.6,0.545455,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.607356,5.0,23.036300
47,47,0.5,0.714286,"(0, 0)\t1.7320508075688772\n (0, 3)\t1.0\n ...",4.419034,6.0,25.308363
48,48,0.6,0.666667,"(0, 0)\t1.0\n (0, 4)\tnan\n (1, 1)\t1.4142...",1.607356,5.0,23.036300
49,49,0.5,0.714286,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.009274,7.0,26.335117

In [28]:
np.mean(sim10)

Unnamed: 0    24.500000
tp             0.610000
acc            0.636655
spec_dist      2.300870
edit           5.160000
netsmile      23.258368
dtype: float64

In [29]:
sim5 = pd.read_csv("sim_sub5.csv")

In [7]:
sim5

,Unnamed: 0,tp,acc,Euclidean_dist,spec_dist,edit,netsmile
0,0,0.5,0.714286,"(0, 0)\t1.7320508075688772\n (0, 3)\t1.0\n ...",4.419034e+00,6.0,25.308363
1,1,0.6,0.750000,"(0, 0)\t1.0\n (0, 3)\t1.0\n (3, 0)\t1.0\n ...",2.281076e+00,2.0,24.285558
2,2,0.5,0.555556,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",2.281076e+00,6.0,24.285558
3,3,0.7,0.538462,"(0, 0)\t1.7320508075688772\n (0, 1)\t1.0\n ...",3.009274e+00,5.0,27.939845
4,4,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.514952e+00,6.0,20.815851
5,5,0.7,0.583333,"(0, 0)\t1.0\n (0, 1)\t1.0\n (0, 2)\tnan\n ...",1.704043e+00,7.0,23.683258
6,6,0.7,1.000000,"(0, 0)\t1.0\n (0, 3)\t1.0\n (2, 2)\t1.0\n ...",3.325016e+00,3.0,24.202346
7,7,0.5,0.625000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.325016e+00,5.0,24.202346
8,8,0.6,0.500000,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",3.009274e+00,6.0,26.313835
9,9,0.7,0.500000,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",9.683709e-01,6.0,20.697713
10,10,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.489341e-15,6.0,18.000000
11,11,0.8,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",2.281076e+00,6.0,23.059793
12,12,0.7,0.700000,"(1, 1)\t1.0\n (1, 2)\tnan\n (1, 4)\tnan\n ...",1.704043e+00,3.0,20.847240
13,13,0.9,0.600000,"(0, 0)\t1.0\n (0, 1)\tnan\n (1, 0)\tnan\n ...",1.607356e+00,3.0,22.949618
14,14,0.8,0.800000,"(1, 1)\t1.0\n (2, 2)\t1.0\n (3, 3)\t1.0\n ...",2.248495e+00,2.0,25.085856
15,15,0.7,0.500000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.414214e+00,5.0,20.829573
16,16,0.7,0.636364,"(0, 0)\t1.4142135623730951\n (0, 1)\t1.0\n ...",1.607356e+00,5.0,23.036300
17,17,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.414214e+00,5.0,22.226172
18,18,0.7,0.583333,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.514952e+00,6.0,24.023737
19,19,0.7,0.700000,"(0, 0)\t1.0\n (0, 2)\tnan\n (0, 4)\tnan\n ...",1.607356e+00,5.0,23.036300
20,20,0.6,0.461538,"(0, 0)\t2.0\n (0, 1)\tnan\n (0, 4)\tnan\n ...",1.414214e+00,9.0,20.829573
21,21,0.7,0.538462,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.607356e+00,5.0,22.949618
22,22,0.5,0.500000,"(0, 0)\t2.0\n (0, 2)\tnan\n (0, 3)\tnan\n ...",1.414214e+00,9.0,22.226172
23,23,0.7,0.700000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.281076e+00,4.0,24.285558
24,24,0.7,0.583333,"(0, 0)\t1.0\n (0, 1)\tnan\n (0, 2)\tnan\n ...",1.704043e+00,5.0,23.683258
25,25,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.607356e+00,4.0,25.923601
26,26,0.6,0.666667,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",2.248495e+00,6.0,25.085856
27,27,0.5,0.500000,"(0, 0)\t1.7320508075688772\n (0, 4)\tnan\n ...",2.281076e+00,8.0,24.285558
28,28,0.5,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.607356e+00,7.0,23.036300
29,29,0.5,0.500000,"(1, 1)\t1.7320508075688772\n (1, 3)\tnan\n ...",1.514952e+00,4.0,24.023737
30,30,0.6,0.500000,"(1, 1)\t1.4142135623730951\n (1, 4)\tnan\n ...",1.438828e-15,4.0,18.000000
31,31,0.6,0.666667,"(0, 0)\t1.4142135623730951\n (0, 1)\t1.0\n ...",1.704043e+00,5.0,20.847240
32,32,0.6,0.750000,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",3.009274e+00,5.0,26.335117
33,33,0.6,0.666667,"(0, 0)\t1.0\n (0, 2)\t1.0\n (0, 3)\tnan\n ...",2.248495e+00,4.0,25.085856
34,34,0.7,0.583333,"(0, 0)\t1.0\n (0, 2)\t1.0\n (0, 3)\tnan\n ...",1.607356e+00,5.0,22.949618
35,35,0.7,0.500000,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",2.248495e+00,4.0,25.012579
36,36,0.8,0.666667,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.514952e+00,4.0,24.023737
37,37,0.8,0.533333,"(0, 0)\t1.0\n (0, 1)\tnan\n (0, 3)\tnan\n ...",1.704043e+00,5.0,23.683258
38,38,0.6,0.500000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",9.940420e-16,6.0,18.000000
39,39,0.7,0.636364,"(0, 0)\t1.0\n (0, 2)\tnan\n (1, 1)\t1.0\n ...",1.514952e+00,4.0,20.815851
40,40,0.7,0.538462,"(1, 1)\t1.0\n (1, 3)\tnan\n (3, 1)\tnan\n ...",1.514952e+00,2.0,24.023737
41,41,0.7,0.538462,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.248495e+00,5.0,25.685973
42,42,0.8,0.615385,"(0, 0)\t1.0\n (0, 3)\tnan\n (1, 1)\t1.0\n ...",1.704043e+00,3.0,23.683258
43,43,0.5,0.625000,"(0, 0)\t1.7320508075688772\n (0, 3)\t1.0\n ...",2.281076e+00,4.0,24.285558
44,44,0.7,0.538462,"(0, 0)\t1.0\n (0, 1)\tnan\n (1, 0)\tnan\n ...",1.514952e+00,2.0,20.815851
45,45,0.6,0.400000,"(0, 0)\t2.0\n (0, 2)\tnan\n (0, 4)\tnan\n ...",2.281076e+00,8.0,23.059793
46,46,0.7,0.700000,"(0, 0)\t1.0\n (0, 2)\t1.0\n (0, 4)\tnan\n ...",1.704043e+00,5.0,20.847240
47,47,0.9,0.600000,"(0, 0)\t1.0\n (0, 2)\tnan\n (1, 1)\t1.0\n ...",1.704043e+00,3.0,23.683258
48,48,0.6,0.600000,"(0, 0)\t2.0\n (0, 1)\tnan\n (0, 2)\tnan\n ...",2.248495e+00,7.0,24.084033
49,49,0.7,0.700000,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.414214e+00,5.0,22.226172

In [30]:
np.mean(sim5)

Unnamed: 0    24.500000
tp             0.662000
acc            0.598903
spec_dist      1.861666
edit           4.980000
netsmile      23.166132
dtype: float64

In [11]:
sim1 = pd.read_csv("sim_sub1.csv")

In [12]:
sim1

,Unnamed: 0,tp,acc,Euclidean_dist,spec_dist,edit,netsmile
0,0,0.7,0.636364,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.248495e+00,3.0,24.084033
1,1,0.6,0.461538,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.607356e+00,6.0,25.923601
2,2,0.8,0.500000,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",2.281076e+00,6.0,23.059793
3,3,0.6,0.600000,"(0, 0)\t1.0\n (0, 1)\tnan\n (0, 2)\tnan\n ...",1.607356e+00,6.0,21.694556
4,4,0.5,0.384615,"(0, 0)\t1.0\n (0, 1)\t1.0\n (0, 2)\tnan\n ...",1.704043e+00,7.0,23.683258
5,5,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.607356e+00,5.0,22.949618
6,6,0.7,0.636364,"(0, 0)\t2.0\n (0, 2)\tnan\n (0, 3)\tnan\n ...",1.414214e+00,5.0,22.226172
7,7,0.8,0.571429,"(0, 0)\t1.0\n (0, 1)\tnan\n (0, 3)\tnan\n ...",1.607356e+00,5.0,22.949618
8,8,0.7,0.500000,"(0, 0)\t1.4142135623730951\n (0, 1)\t1.0\n ...",1.414214e+00,5.0,20.829573
9,9,0.8,0.421053,"(0, 0)\t1.7320508075688772\n (0, 1)\t1.0\n ...",4.419034e+00,6.0,24.304011
10,10,0.7,0.636364,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.248495e+00,5.0,24.084033
11,11,0.7,0.875000,"(0, 0)\t1.0\n (1, 1)\t1.0\n (1, 3)\t1.0\n ...",3.009274e+00,3.0,26.335117
12,12,0.7,0.636364,"(0, 0)\t1.0\n (0, 2)\tnan\n (1, 1)\t1.0\n ...",1.607356e+00,3.0,23.036300
13,13,0.6,0.500000,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",1.607356e+00,6.0,25.923601
14,14,0.8,0.666667,"(0, 0)\t1.0\n (1, 1)\t1.4142135623730951\n ...",1.704043e+00,3.0,23.683258
15,15,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 1)\t1.0\n ...",1.607356e+00,5.0,23.036300
16,16,0.9,0.562500,"(0, 0)\t1.0\n (0, 4)\t1.0\n (1, 1)\t1.0\n ...",3.009274e+00,3.0,26.240807
17,17,0.8,0.470588,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",2.281076e+00,4.0,23.059793
18,18,0.8,0.666667,"(0, 0)\t1.0\n (0, 1)\tnan\n (1, 0)\tnan\n ...",1.414214e+00,3.0,20.829573
19,19,0.5,0.555556,"(0, 0)\t1.4142135623730951\n (0, 4)\tnan\n ...",1.607356e+00,5.0,23.036300
20,20,0.5,0.555556,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.414214e+00,7.0,22.226172
21,21,0.5,0.500000,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",3.231037e-15,4.0,18.000000
22,22,0.7,0.538462,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.414214e+00,5.0,20.829573
23,23,0.7,0.466667,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.281076e+00,4.0,23.059793
24,24,0.6,0.428571,"(1, 1)\t1.7320508075688772\n (1, 3)\t1.0\n ...",1.607356e+00,5.0,22.949618
25,25,0.6,0.500000,"(0, 0)\t1.4142135623730951\n (0, 1)\t1.0\n ...",1.748064e+00,7.0,23.442274
26,26,0.6,0.600000,"(0, 0)\t2.0\n (0, 2)\tnan\n (0, 3)\tnan\n ...",1.414214e+00,5.0,22.226172
27,27,0.8,0.800000,"(0, 0)\t1.0\n (2, 2)\t1.0\n (3, 3)\t1.0\n ...",2.248495e+00,2.0,25.085856
28,28,0.5,0.555556,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",1.704043e+00,7.0,20.847240
29,29,0.7,0.700000,"(0, 0)\t1.7320508075688772\n (0, 3)\t1.0\n ...",3.009274e+00,4.0,22.524219
30,30,0.6,0.500000,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",1.514952e+00,6.0,20.815851
31,31,0.6,0.600000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.704043e+00,7.0,20.847240
32,32,0.8,0.727273,"(0, 0)\t1.4142135623730951\n (0, 3)\tnan\n ...",1.414214e+00,3.0,22.226172
33,33,0.7,0.636364,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.607356e+00,5.0,23.036300
34,34,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",2.281076e+00,4.0,24.285558
35,35,0.7,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.009274e+00,6.0,26.313835
36,36,0.5,0.555556,"(0, 0)\t1.0\n (0, 1)\tnan\n (0, 3)\tnan\n ...",1.607356e+00,5.0,23.036300
37,37,0.6,0.545455,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.514952e+00,6.0,24.023737
38,38,0.7,0.700000,"(0, 0)\t1.0\n (1, 1)\t1.4142135623730951\n ...",1.704043e+00,3.0,20.847240
39,39,0.8,0.666667,"(0, 0)\t1.4142135623730951\n (0, 2)\tnan\n ...",1.414214e+00,3.0,22.226172
40,40,0.7,0.538462,"(0, 0)\t2.0\n (0, 1)\tnan\n (0, 2)\tnan\n ...",1.414214e+00,7.0,20.829573
41,41,0.6,0.500000,"(0, 0)\t2.0\n (0, 2)\tnan\n (0, 3)\t1.0\n ...",1.607356e+00,6.0,21.694556
42,42,0.7,0.500000,"(0, 0)\t1.0\n (0, 3)\tnan\n (0, 4)\t1.0\n ...",3.009274e+00,4.0,26.313835
43,43,0.6,0.500000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.704043e+00,7.0,20.847240
44,44,0.7,0.466667,"(0, 0)\t1.7320508075688772\n (0, 2)\tnan\n ...",1.704043e+00,7.0,23.683258
45,45,0.7,0.583333,"(0, 0)\t1.0\n (0, 1)\tnan\n (1, 0)\tnan\n ...",9.683709e-01,4.0,20.697713
46,46,0.8,0.666667,"(0, 0)\t1.0\n (0, 3)\tnan\n (0, 4)\t1.0\n ...",1.607356e+00,4.0,25.923601
47,47,0.6,0.545455,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",1.704043e+00,7.0,20.847240
48,48,0.7,0.583333,"(0, 0)\t1.4142135623730951\n (0, 2)\t1.0\n ...",1.607356e+00,4.0,25.923601
49,49,0.6,0.600000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.248495e+00,6.0,25.085856

In [13]:
np.mean(sim1)

Unnamed: 0    24.500000
tp             0.670000
acc            0.572489
spec_dist      1.843865
edit           4.960000
netsmile      23.033302
dtype: float64

In [38]:
sim1 = pd.read_csv("tau_result/patel_tau sim1.csv")

In [39]:
sim1

,Unnamed: 0,tp,acc,Euclidean_dist,spec_dist,edit,netsmile
0,0,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
1,1,0.6,0.300000,"(0, 0)\t1.7320508075688772\n (0, 2)\t1.0\n ...",1.514952,6.5,25.914350
2,2,0.8,0.444444,"(0, 0)\t1.0\n (1, 1)\t1.4142135623730951\n ...",1.414214,3.5,23.675060
3,3,0.6,0.375000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",2.281076,4.5,24.341686
4,4,0.4,0.285714,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.325016,5.5,23.768353
5,5,0.2,0.166667,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",4.419034,6.5,23.710816
6,6,0.4,0.250000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.009274,6.5,22.767003
7,7,1.0,0.454545,"(0, 0)\t1.4142135623730951\n (0, 2)\t1.4142...",1.414214,3.5,22.692568
8,8,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
9,9,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
10,10,0.6,0.333333,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",1.607356,5.5,24.688176
11,11,0.6,0.375000,"(0, 0)\t1.0\n (1, 1)\t1.4142135623730951\n ...",2.281076,4.5,24.341686
12,12,0.4,0.285714,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",3.009274,5.5,25.749733
13,13,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
14,14,0.4,0.285714,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",3.009274,5.5,25.749733
15,15,0.4,0.250000,"(0, 0)\t2.0\n (0, 1)\tnan\n (0, 2)\t1.4142...",3.009274,6.5,22.767003
16,16,0.4,0.285714,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.009274,5.5,25.749733
17,17,0.4,0.285714,"(0, 0)\t1.4142135623730951\n (0, 4)\tnan\n ...",3.009274,5.5,25.749733
18,18,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
19,19,0.4,0.285714,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.325016,5.5,23.768353
20,20,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
21,21,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
22,22,0.4,0.285714,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.325016,5.5,23.768353
23,23,0.4,0.285714,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",3.325016,5.5,23.768353
24,24,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
25,25,0.4,0.285714,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.325016,5.5,23.768353
26,26,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
27,27,0.2,0.166667,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",4.419034,6.5,23.710816
28,28,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
29,29,0.4,0.250000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",3.009274,6.5,22.767003
30,30,0.2,0.166667,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",4.419034,6.5,23.710816
31,31,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
32,32,0.4,0.222222,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",3.009274,7.5,24.022371
33,33,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
34,34,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
35,35,0.6,0.375000,"(0, 0)\t1.0\n (1, 1)\t1.4142135623730951\n ...",2.281076,4.5,24.341686
36,36,0.2,0.142857,"(0, 0)\t2.0\n (0, 1)\tnan\n (0, 2)\t1.4142...",3.325016,7.5,23.768353
37,37,0.8,0.444444,"(0, 0)\t1.0\n (1, 1)\t1.0\n (2, 2)\t1.0\n ...",1.414214,3.5,23.675060
38,38,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
39,39,0.6,0.375000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",2.248495,4.5,25.141985
40,40,0.2,0.166667,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
41,41,0.2,0.166667,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",4.419034,6.5,23.710816
42,42,0.6,0.375000,"(0, 0)\t1.4142135623730951\n (0, 3)\t1.0\n ...",2.281076,4.5,24.341686
43,43,0.2,0.125000,"(0, 0)\t1.4142135623730951\n (0, 1)\tnan\n ...",3.009274,8.5,22.767003
44,44,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
45,45,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
46,46,0.2,0.166667,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",4.419034,6.5,23.710816
47,47,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
48,48,0.0,0.000000,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",5.477226,7.5,23.333333
49,49,0.4,0.285714,"(0, 0)\t1.7320508075688772\n (0, 1)\tnan\n ...",3.325016,5.5,23.768353

In [33]:
np.mean(sim1)

Unnamed: 0    24.500000
tp             0.312000
acc            0.205646
spec_dist      3.714701
edit           6.180000
netsmile      23.858130
dtype: float64

In [34]:
sim1_25 = pd.read_csv("tau_result/patel_tau sim1 bin25%.csv")

In [40]:
sim1_75 = pd.read_csv("tau_result/patel_tau sim1 bin75%.csv")
np.mean(sim1_75)

Unnamed: 0    24.500000
tp             0.808000
acc            0.344464
spec_dist      2.450752
edit           6.040000
netsmile      24.798640
dtype: float64

In [42]:
sim5 = pd.read_csv("tau_result/patel_tau sim5.csv")
np.mean(sim5)

Unnamed: 0    24.500000
tp             0.312000
acc            0.199935
spec_dist      3.686671
edit           6.220000
netsmile      23.835233
dtype: float64

In [45]:
sim5_75 = pd.read_csv("tau_result/patel_tau sim5 bin75%.csv")
np.mean(sim5_75)

Unnamed: 0    24.500000
tp             0.796000
acc            0.345897
spec_dist      2.484034
edit           6.000000
netsmile      24.866865
dtype: float64

In [3]:
sim6_75 = pd.read_csv("tau_result/patel_tau sim6 bin75%.csv")
np.mean(sim6_75)

Unnamed: 0    24.500000
tp             0.709091
acc            0.323020
spec_dist      3.848609
edit          14.680000
netsmile      20.459973
dtype: float64

In [47]:
sim10 = pd.read_csv("tau_result/patel_tau sim10.csv")
np.mean(sim10)

tp            0.396000
acc           0.224279
spec_dist     2.923414
edit          6.580000
netsmile     23.502627
dtype: float64

In [50]:
sim10_75 = pd.read_csv("tau_result/patel_tau sim10 bin75%.csv")
np.mean(sim10_75)

Unnamed: 0    24.500000
tp             0.844000
acc            0.328056
spec_dist      3.295451
edit           6.900000
netsmile      25.480849
dtype: float64

In [4]:
sim12_75 = pd.read_csv("tau_result/patel_tau sim12 bin75%.csv")
np.mean(sim12_75)

Unnamed: 0    24.500000
tp             0.045455
acc            0.042692
spec_dist      7.956935
edit          15.600000
netsmile      24.210097
dtype: float64

In [8]:
sim17_75 = pd.read_csv("tau_result/patel_tau sim17 bin75%.csv")
np.mean(sim17_75)

Unnamed: 0    24.500000
tp             0.000000
acc                 NaN
spec_dist      8.485281
edit          11.000000
netsmile      31.147212
dtype: float64

In [7]:
sim19_75 = pd.read_csv("tau_result/patel_tau sim19 bin75%.csv")
np.mean(sim19_75)

Unnamed: 0    24.500000
tp             0.000000
acc                 NaN
spec_dist      5.477226
edit           5.000000
netsmile      28.000000
dtype: float64

In [9]:
sim20_75 = pd.read_csv("tau_result/patel_tau sim20 bin75%.csv")
np.mean(sim20_75)

Unnamed: 0    24.500000
tp             0.148000
acc            0.114286
spec_dist      4.620128
edit           6.840000
netsmile      23.609381
dtype: float64

In [4]:
sim7 = pd.read_csv("tau_result/patel_tau sim7.csv")
np.mean(sim7)

tp            0.292000
acc           0.195558
spec_dist     3.751836
edit          6.320000
netsmile     23.687608
dtype: float64

In [8]:
sim7_75 = pd.read_csv("tau_result/patel_tau sim7 bin75%.csv")
np.mean(sim7_75)

Unnamed: 0    24.500000
tp             0.828000
acc            0.350085
spec_dist      2.645430
edit           6.000000
netsmile      24.864679
dtype: float64

In [10]:
neuro_sim7 = pd.read_csv("neuralODE_simu_result/sim_sub7.csv")
np.mean(neuro_sim7)

Unnamed: 0    24.50000
tp             0.71000
acc            0.54635
spec_dist      2.06465
edit           4.48000
netsmile      22.95956
dtype: float64

In [11]:
sim8 = pd.read_csv("tau_result/patel_tau sim8.csv")
np.mean(sim8)

Unnamed: 0    24.500000
tp             0.468000
acc            0.241211
spec_dist      2.911647
edit           6.520000
netsmile      23.974528
dtype: float64

In [15]:
sim8_75 = pd.read_csv("tau_result/patel_tau sim8 bin75%.csv")
np.mean(sim8_75)

Unnamed: 0    24.500000
tp             0.840000
acc            0.329377
spec_dist      3.340316
edit           6.840000
netsmile      25.326663
dtype: float64

In [17]:
neuro_sim8 = pd.read_csv("neuralODE_simu_result/sim_sub8.csv")
np.mean(neuro_sim8)

Unnamed: 0    24.500000
tp             0.708000
acc            0.509222
spec_dist      2.428192
edit           5.220000
netsmile      23.138901
dtype: float64

In [18]:
neuro_sim9 = pd.read_csv("neuralODE_simu_result/sim_sub9.csv")
np.mean(neuro_sim9)

Unnamed: 0    24.500000
tp             0.724000
acc            0.509172
spec_dist      2.457626
edit           4.800000
netsmile      23.647937
dtype: float64

In [20]:
sim9 = pd.read_csv("tau_result/patel_tau sim9.csv")
np.mean(sim9)

Unnamed: 0    24.500000
tp             0.472000
acc            0.243172
spec_dist      2.426026
edit           7.100000
netsmile      23.878663
dtype: float64

In [22]:
sim9_75 = pd.read_csv("tau_result/patel_tau sim9 bin75%.csv")
np.mean(sim9_75)

Unnamed: 0    24.500000
tp             0.888000
acc            0.332380
spec_dist      3.754743
edit           6.980000
netsmile      25.894507
dtype: float64

In [4]:
sim13 = pd.read_csv("tau_result/patel_tau sim13.csv")
np.mean(sim13)

tp            0.148000
acc           0.111429
spec_dist     4.617461
edit          6.820000
netsmile     23.661120
dtype: float64

In [5]:
sim13_75 = pd.read_csv("tau_result/patel_tau sim13 bin75%.csv")
np.mean(sim13_75)

Unnamed: 0    24.500000
tp             0.596000
acc            0.280934
spec_dist      2.017570
edit           6.880000
netsmile      24.088155
dtype: float64

In [8]:
sim14 = pd.read_csv("tau_result/patel_tau sim14.csv")
np.mean(sim14)

Unnamed: 0    24.500000
tp             0.196000
acc            0.122931
spec_dist      3.956831
edit           6.680000
netsmile      23.655418
dtype: float64

In [7]:
sim14_75 = pd.read_csv("tau_result/patel_tau sim14 bin75%.csv")
np.mean(sim14_75)

Unnamed: 0    24.500000
tp             0.620000
acc            0.262610
spec_dist      2.769112
edit           6.420000
netsmile      25.216924
dtype: float64

In [9]:
sim15 = pd.read_csv("tau_result/patel_tau sim15.csv")
np.mean(sim15)

Unnamed: 0    24.500000
tp             0.712000
acc            0.294921
spec_dist      2.865121
edit           7.400000
netsmile      24.940900
dtype: float64

In [10]:
sim15_75 = pd.read_csv("tau_result/patel_tau sim15 bin75%.csv")
np.mean(sim15_75)

Unnamed: 0    24.500000
tp             0.952000
acc            0.330348
spec_dist      4.828462
edit           7.380000
netsmile      25.536546
dtype: float64

In [11]:
sim16 = pd.read_csv("tau_result/patel_tau sim16.csv")
np.mean(sim16)

Unnamed: 0    24.500000
tp             0.371429
acc            0.295032
spec_dist      4.173322
edit           7.360000
netsmile      20.470986
dtype: float64

In [12]:
sim16_75 = pd.read_csv("tau_result/patel_tau sim16 bin75%.csv")
np.mean(sim16_75)

Unnamed: 0    24.500000
tp             0.857143
acc            0.458805
spec_dist      1.837523
edit           5.560000
netsmile      15.740728
dtype: float64

In [19]:
sim18 = pd.read_csv("tau_result/patel_tau sim18.csv")
np.mean(sim18)

Unnamed: 0    24.500000
tp             0.228000
acc            0.165714
spec_dist      4.058471
edit           6.560000
netsmile      23.833504
dtype: float64

In [20]:
sim18_75 = pd.read_csv("tau_result/patel_tau sim18 bin75%.csv")
np.mean(sim18_75)

Unnamed: 0    24.500000
tp             0.740000
acc            0.323166
spec_dist      2.501574
edit           6.460000
netsmile      25.076925
dtype: float64

In [21]:
sim21 = pd.read_csv("tau_result/patel_tau sim21.csv")
np.mean(sim21)

Unnamed: 0    24.500000
tp             0.300000
acc            0.197829
spec_dist      3.768020
edit           6.220000
netsmile      23.889305
dtype: float64

In [22]:
sim21_75 = pd.read_csv("tau_result/patel_tau sim21 bin75%.csv")
np.mean(sim21_75)

Unnamed: 0    24.500000
tp             0.796000
acc            0.349009
spec_dist      2.384252
edit           5.840000
netsmile      25.183261
dtype: float64

In [24]:
sim22 = pd.read_csv("tau_result/patel_tau sim22.csv")
np.mean(sim22)

Unnamed: 0    24.500000
tp             0.348000
acc            0.220793
spec_dist      3.287711
edit           6.320000
netsmile      23.939138
dtype: float64

In [26]:
sim22_75 = pd.read_csv("tau_result/patel_tau sim22 bin75%.csv")
np.mean(sim22_75)

Unnamed: 0    24.500000
tp             0.828000
acc            0.329922
spec_dist      2.978655
edit           6.780000
netsmile      25.751678
dtype: float64

In [27]:
sim23_75 = pd.read_csv("tau_result/patel_tau sim23 bin75%.csv")
np.mean(sim23_75)

Unnamed: 0    24.500000
tp             0.932000
acc            0.321923
spec_dist      4.860310
edit           7.620000
netsmile      25.660803
dtype: float64

In [28]:
sim24_75 = pd.read_csv("tau_result/patel_tau sim24 bin75%.csv")
np.mean(sim24_75)

Unnamed: 0    24.500000
tp             0.900000
acc            0.316703
spec_dist      4.554876
edit           7.660000
netsmile      25.345398
dtype: float64

In [29]:
sim25_75 = pd.read_csv("tau_result/patel_tau sim25 bin75%.csv")
np.mean(sim25_75)

Unnamed: 0    24.500000
tp             0.968000
acc            0.336374
spec_dist      4.818350
edit           7.220000
netsmile      25.699559
dtype: float64

In [30]:
sim28_75 = pd.read_csv("tau_result/patel_tau sim28 bin75%.csv")
np.mean(sim28_75)

Unnamed: 0    24.500000
tp             0.832000
acc            0.332379
spec_dist      2.975092
edit           6.700000
netsmile      25.501653
dtype: float64

In [31]:
sim2_75 = pd.read_csv("tau_result/patel_tau sim2 bin75%.csv")
np.mean(sim2_75)

Unnamed: 0    24.500000
tp             0.796364
acc            0.252430
spec_dist      9.679543
edit          23.300000
netsmile      23.675835
dtype: float64

In [32]:
sim3_75 = pd.read_csv("tau_result/patel_tau sim2 bin75%.csv")
np.mean(sim3_75)

Unnamed: 0    24.500000
tp             0.796364
acc            0.252430
spec_dist      9.679543
edit          23.300000
netsmile      23.675835
dtype: float64

In [52]:
sim11_75 = pd.read_csv("tau_result/patel_tau sim11 bin75%.csv")
np.mean(sim11_75)

Unnamed: 0    24.500000
tp             0.100000
acc            0.081341
spec_dist      6.873195
edit          15.800000
netsmile      21.098605
dtype: float64

In [40]:
sim12_75 = pd.read_csv("tau_result/patel_tau sim12 bin75%.csv")
np.mean(sim12_75)

Unnamed: 0    24.500000
tp             0.045455
acc            0.042692
spec_dist      7.956935
edit          15.600000
netsmile      24.210097
dtype: float64

In [13]:
neuro_sim13 = pd.read_csv("neuralODE_simu_result/sim_sub13.csv")
np.mean(neuro_sim13)

Unnamed: 0    24.500000
tp             0.629790
acc            0.600582
spec_dist      1.933665
edit           5.080000
netsmile      23.221846
dtype: float64

In [14]:
neuro_sim14 = pd.read_csv("neuralODE_simu_result/sim_sub14.csv")
np.mean(neuro_sim14)

Unnamed: 0    24.500000
tp             0.740000
acc            0.541743
spec_dist      2.171263
edit           4.910000
netsmile      23.024092
dtype: float64

In [15]:
neuro_sim15 = pd.read_csv("neuralODE_simu_result/sim_sub15.csv")
np.mean(neuro_sim15)

Unnamed: 0    24.500000
tp             0.742000
acc            0.489718
spec_dist      3.247114
edit           4.820000
netsmile      23.866091
dtype: float64

In [16]:
neuro_sim16 = pd.read_csv("neuralODE_simu_result/sim_sub16.csv")
np.mean(neuro_sim16)

Unnamed: 0    24.500000
tp             0.675000
acc            0.594677
spec_dist      1.854528
edit           4.650000
netsmile      14.067161
dtype: float64

In [17]:
neuro_sim18 = pd.read_csv("neuralODE_simu_result/sim_sub18.csv")
np.mean(neuro_sim18)

Unnamed: 0    24.500000
tp             0.736000
acc            0.541103
spec_dist      2.384966
edit           4.820000
netsmile      23.734940
dtype: float64

In [18]:
neuro_sim21 = pd.read_csv("neuralODE_simu_result/sim_sub21.csv")
np.mean(neuro_sim21)

Unnamed: 0    24.500000
tp             0.720000
acc            0.535544
spec_dist      2.277647
edit           5.000000
netsmile      23.325799
dtype: float64

In [42]:
neuro_sim22 = pd.read_csv("neuralODE_simu_result/sim_sub22.csv")
np.mean(neuro_sim22)

Unnamed: 0    24.500000
tp             0.708000
acc            0.585974
spec_dist      2.202835
edit           4.730000
netsmile      23.442792
dtype: float64

In [43]:
neuro_sim23 = pd.read_csv("neuralODE_simu_result/sim_sub23.csv")
np.mean(neuro_sim23)

Unnamed: 0    24.500000
tp             0.732000
acc            0.461075
spec_dist      4.044127
edit           5.150000
netsmile      24.819036
dtype: float64

In [44]:
neuro_sim24 = pd.read_csv("neuralODE_simu_result/sim_sub24.csv")
np.mean(neuro_sim24)

Unnamed: 0    24.500000
tp             0.714000
acc            0.432893
spec_dist      4.163724
edit           5.420000
netsmile      24.716603
dtype: float64

In [45]:
neuro_sim25 = pd.read_csv("neuralODE_simu_result/sim_sub25.csv")
np.mean(neuro_sim25)

Unnamed: 0    24.500000
tp             0.584000
acc            0.638942
spec_dist      2.174404
edit           4.950000
netsmile      23.591713
dtype: float64

In [46]:
neuro_sim28 = pd.read_csv("neuralODE_simu_result/sim_sub28.csv")
np.mean(neuro_sim28)

Unnamed: 0    24.500000
tp             0.536000
acc            0.605782
spec_dist      2.025777
edit           5.100000
netsmile      23.375582
dtype: float64

In [23]:
neuro_sim2 = pd.read_csv("neuralODE_simu_result/sim_sub2.csv")
np.mean(neuro_sim2)

Unnamed: 0    24.500000
tp             0.592381
acc            0.440079
spec_dist      4.047513
edit          18.700000
netsmile      20.607519
dtype: float64

In [47]:
neuro_sim3 = pd.read_csv("neuralODE_simu_result/sim_sub3.csv")
np.mean(neuro_sim3)

Unnamed: 0    24.500000
tp             0.547273
acc            0.411895
spec_dist      5.563897
edit          34.300000
netsmile      16.827649
dtype: float64

In [50]:
neuro_sim11 = pd.read_csv("neuralODE_simu_result/sim_sub11.csv")
np.mean(neuro_sim11)

Unnamed: 0    24.500000
tp             0.589524
acc            0.428543
spec_dist      4.434237
edit          19.030000
netsmile      20.764809
dtype: float64

In [6]:
for i in range(1,4):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

1 Unnamed: 0    24.500000
tp             0.994000
acc            0.400159
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
2 Unnamed: 0    24.500000
tp             0.998095
acc            0.210572
spec_dist     23.065125
edit          34.000000
netsmile      29.243786
dtype: float64
3 Unnamed: 0    24.500000
tp             0.995758
acc            0.146947
spec_dist     46.925473
edit          87.000000
netsmile      30.990855
dtype: float64

In [8]:
for i in range(5,8):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

5 Unnamed: 0    24.500000
tp             0.992000
acc            0.398667
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
6 Unnamed: 0    24.500000
tp             0.999048
acc            0.210950
spec_dist     23.065125
edit          34.000000
netsmile      29.243786
dtype: float64
7 Unnamed: 0    24.500000
tp             1.000000
acc            0.401029
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64

In [10]:
for i in range(8,9):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

8 Unnamed: 0    24.500000
tp             0.996000
acc            0.401000
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64

In [12]:
for i in range(10,14):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

10 Unnamed: 0    24.500000
tp             1.000000
acc            0.400667
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
11 Unnamed: 0    24.500000
tp             0.997143
acc            0.210456
spec_dist     23.065125
edit          34.000000
netsmile      29.243786
dtype: float64
12 Unnamed: 0    24.500000
tp             0.999048
acc            0.210818
spec_dist     23.065125
edit          34.000000
netsmile      29.243786
dtype: float64
13 Unnamed: 0    24.500000
tp             0.992051
acc            0.484333
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64

In [14]:
for i in range(15,16):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

15 Unnamed: 0    24.500000
tp             0.996000
acc            0.399000
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64

In [15]:
for i in range(17,26):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

17 Unnamed: 0    24.500000
tp             0.999048
acc            0.210778
spec_dist     23.065125
edit          34.000000
netsmile      29.243786
dtype: float64
18 Unnamed: 0    24.500000
tp             0.998000
acc            0.399500
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
19 Unnamed: 0    24.500000
tp             0.990000
acc            0.402478
spec_dist      5.477226
edit           5.030000
netsmile      24.072507
dtype: float64
20 Unnamed: 0    24.500000
tp             0.990000
acc            0.400819
spec_dist      5.477226
edit           5.010000
netsmile      23.957502
dtype: float64
21 Unnamed: 0    24.500000
tp             0.996000
acc            0.400333
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
22 Unnamed: 0    24.500000
tp             1.000000
acc            0.401333
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
23 Unnamed: 0    24.500000
tp             1.000000
acc            0.401333
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
24 Unnamed: 0    24.500000
tp             1.000000
acc            0.401333
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
25 Unnamed: 0    24.500000
tp             0.998000
acc            0.401833
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64

In [16]:
i = 28
neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.01/sim_sub{i}.csv")
print(i, np.mean(neuro_sim))

28 Unnamed: 0    24.500000
tp             0.998000
acc            0.400500
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64

In [17]:
for i in range(1,4):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.1/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

1 Unnamed: 0    24.500000
tp             0.972000
acc            0.408172
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
2 Unnamed: 0    24.500000
tp             0.977143
acc            0.216359
spec_dist     23.003099
edit          33.920000
netsmile      29.020190
dtype: float64
3 Unnamed: 0    24.500000
tp             0.965455
acc            0.151260
spec_dist     46.677449
edit          86.780000
netsmile      29.745637
dtype: float64

In [18]:
for i in range(5,9):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.1/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

5 Unnamed: 0    24.500000
tp             0.984000
acc            0.407294
spec_dist      5.456062
edit           4.980000
netsmile      23.908080
dtype: float64
6 Unnamed: 0    24.500000
tp             0.967619
acc            0.215604
spec_dist     22.925565
edit          33.900000
netsmile      28.740695
dtype: float64
7 Unnamed: 0    24.500000
tp             0.978000
acc            0.407057
spec_dist      5.413734
edit           5.020000
netsmile      23.924241
dtype: float64
8 Unnamed: 0    24.500000
tp             0.988000
acc            0.406905
spec_dist      5.434898
edit           5.000000
netsmile      23.916160
dtype: float64

In [20]:
for i in range(10,15):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.1/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

10 Unnamed: 0    24.500000
tp             0.986000
acc            0.411032
spec_dist      5.434898
edit           4.960000
netsmile      23.916160
dtype: float64
11 Unnamed: 0    24.500000
tp             0.978095
acc            0.215112
spec_dist     22.897791
edit          33.900000
netsmile      28.616975
dtype: float64
12 Unnamed: 0    24.500000
tp             0.971429
acc            0.215274
spec_dist     22.972085
edit          33.920000
netsmile      28.908392
dtype: float64
13 Unnamed: 0    24.500000
tp             0.979883
acc            0.490016
spec_dist      5.477226
edit           5.000000
netsmile      23.900000
dtype: float64
14 Unnamed: 0    24.500000
tp             0.984000
acc            0.406673
spec_dist      5.456062
edit           5.020000
netsmile      23.908080
dtype: float64

In [24]:
for i in range(15,25):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.1/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

15 Unnamed: 0    24.500000
tp             0.986000
acc            0.405395
spec_dist      5.434898
edit           4.960000
netsmile      23.916160
dtype: float64
16 Unnamed: 0    24.500000
tp             0.980000
acc            0.481261
spec_dist      3.715814
edit           2.980000
netsmile      25.849610
dtype: float64
17 Unnamed: 0    24.500000
tp             0.976190
acc            0.215245
spec_dist     22.987592
edit          34.020000
netsmile      28.964291
dtype: float64
18 Unnamed: 0    24.500000
tp             0.974000
acc            0.400157
spec_dist      5.456062
edit           5.020000
netsmile      23.908080
dtype: float64
19 Unnamed: 0    24.500000
tp             0.826000
acc            0.406214
spec_dist      5.095560
edit           5.300000
netsmile      25.433624
dtype: float64
20 Unnamed: 0    24.500000
tp             0.798000
acc            0.393740
spec_dist      5.158335
edit           5.420000
netsmile      25.067138
dtype: float64
21 Unnamed: 0    24.500000
tp             0.976000
acc            0.403300
spec_dist      5.456062
edit           4.980000
netsmile      23.908080
dtype: float64
22 Unnamed: 0    24.500000
tp             0.984000
acc            0.412370
spec_dist      5.456062
edit           4.980000
netsmile      23.908080
dtype: float64
23 Unnamed: 0    24.500000
tp             0.972000
acc            0.400602
spec_dist      5.456062
edit           5.070000
netsmile      24.195593
dtype: float64
24 Unnamed: 0    24.500000
tp             0.984000
acc            0.401356
spec_dist      5.434898
edit           5.030000
netsmile      24.059230
dtype: float64

In [26]:
for i in [25,28]:
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.1/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

25 Unnamed: 0    24.500000
tp             0.976000
acc            0.408935
spec_dist      5.434898
edit           5.000000
netsmile      23.916160
dtype: float64
28 Unnamed: 0    24.500000
tp             0.972000
acc            0.410599
spec_dist      5.413734
edit           4.980000
netsmile      23.924241
dtype: float64

In [29]:
for i in range(1,4):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.5/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

1 Unnamed: 0    24.500000
tp             0.882000
acc            0.437320
spec_dist      4.680630
edit           5.020000
netsmile      24.099427
dtype: float64
2 Unnamed: 0    24.500000
tp             0.858095
acc            0.241831
spec_dist     20.412745
edit          32.120000
netsmile      24.543570
dtype: float64
3 Unnamed: 0    24.500000
tp             0.843030
acc            0.176271
spec_dist     40.448233
edit          78.760000
netsmile      23.841311
dtype: float64

In [31]:
for i in range(5,9):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.5/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

5 Unnamed: 0    24.500000
tp             0.900000
acc            0.438548
spec_dist      4.739212
edit           4.720000
netsmile      24.125882
dtype: float64
6 Unnamed: 0    24.500000
tp             0.850476
acc            0.239878
spec_dist     19.977025
edit          31.360000
netsmile      23.881930
dtype: float64
7 Unnamed: 0    24.500000
tp             0.910000
acc            0.440326
spec_dist      4.917272
edit           4.920000
netsmile      24.039882
dtype: float64
8 Unnamed: 0    24.500000
tp             0.900000
acc            0.435233
spec_dist      4.874741
edit           5.000000
netsmile      24.089779
dtype: float64

In [34]:
for i in range(10,15):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.5/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

10 Unnamed: 0    24.500000
tp             0.878000
acc            0.434505
spec_dist      4.939665
edit           4.940000
netsmile      24.099100
dtype: float64
11 Unnamed: 0    24.500000
tp             0.876190
acc            0.242671
spec_dist     20.352960
edit          31.800000
netsmile      24.283793
dtype: float64
12 Unnamed: 0    24.500000
tp             0.878095
acc            0.245460
spec_dist     20.040243
edit          31.280000
netsmile      24.120838
dtype: float64
13 Unnamed: 0    24.500000
tp             0.887156
acc            0.522465
spec_dist      4.670204
edit           4.980000
netsmile      24.223812
dtype: float64
14 Unnamed: 0    24.500000
tp             0.914000
acc            0.433605
spec_dist      4.997559
edit           5.020000
netsmile      24.140537
dtype: float64

In [35]:
for i in range(15,26):
    neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre0.5/sim_sub{i}.csv")
    print(i, np.mean(neuro_sim))

15 Unnamed: 0    24.500000
tp             0.918000
acc            0.419040
spec_dist      5.265587
edit           5.050000
netsmile      24.038305
dtype: float64
16 Unnamed: 0    24.500000
tp             0.868333
acc            0.506230
spec_dist      2.833390
edit           3.080000
netsmile      19.517137
dtype: float64
17 Unnamed: 0    24.500000
tp             0.857143
acc            0.238927
spec_dist     20.344982
edit          32.000000
netsmile      24.413676
dtype: float64
18 Unnamed: 0    24.500000
tp             0.900000
acc            0.440451
spec_dist      4.809518
edit           4.900000
netsmile      24.147563
dtype: float64
19 Unnamed: 0    24.500000
tp             0.244000
acc            0.399243
spec_dist      2.388572
edit           6.910000
netsmile      24.567015
dtype: float64
20 Unnamed: 0    24.500000
tp             0.260000
acc            0.413081
spec_dist      2.535813
edit           6.880000
netsmile      24.275211
dtype: float64
21 Unnamed: 0    24.500000
tp             0.886000
acc            0.428039
spec_dist      4.981277
edit           5.020000
netsmile      24.066158
dtype: float64
22 Unnamed: 0    24.500000
tp             0.904000
acc            0.444814
spec_dist      4.853577
edit           4.900000
netsmile      24.097859
dtype: float64
23 Unnamed: 0    24.500000
tp             0.914000
acc            0.416149
spec_dist      5.307915
edit           5.040000
netsmile      24.365787
dtype: float64
24 Unnamed: 0    24.500000
tp             0.884000
acc            0.402494
spec_dist      5.329079
edit           5.120000
netsmile      24.732159
dtype: float64
25 Unnamed: 0    24.500000
tp             0.872000
acc            0.456015
spec_dist      4.525305
edit           4.890000
netsmile      24.178838
dtype: float64

In [37]:
i= 1
neuro_sim = pd.read_csv(f"neuralODE_simu_result/thre1/sim_sub{i}.csv")
print(i, np.mean(neuro_sim))

1 Unnamed: 0    24.500000
tp             0.774000
acc            0.465481
spec_dist      3.343614
edit           5.020000
netsmile      24.070287
dtype: float64